### ISSUE TITLE
Is there a public API?

### ISSUE THREAD

**Issue by Qocotzxin** [midjourney/docs#43] opened 2022-09-12 14:51 UTC
Hi! I was wondering if there is a public API (free of paid) to connect with, in order to send prompts and get the results, or if there are plans to support something like that? For now it seems the only possibility is do it through Discord channel but this is a blocker to build an app that generates images through your service.

Thanks in advance!

**Comment by SebbyLaw** [comment] 2022-09-12 18:23
Duplicate of #42

**Closed** 2022-09-12 18:25 UTC
